import LeanMath.Papers.V14PolynomialGate

/-! Exact binary64 coefficient values from the archived deployed table.
Source SHA-256: 84d411d2aca757a33ba7e01d397ab7d6db7bb843717e039f61b953b3af23809f
Generated by scripts/generate_v14_deployed.py. Every claim below is checked by Lean.
These positivity certificates do not yet prove the uniform approximation errors. -/
noncomputable section
namespace LeanMath.Papers.V14DeployedCoefficients
open Polynomial
open LeanMath.Papers.V14PolynomialGate

def Pg31 : ℝ[X] := ofCoeffs [(1162219258676257/36028797018963968), (-3319584381680765/4503599627370496), (2925838758887471/1125899906842624), (-8395738696596451/2251799813685248), (1377388413819675/562949953421312), (-5514983533370323/9007199254740992)]
def Qg31 : ℝ[X] := ofCoeffs [1, (-714498461211095/140737488355328), (5899689808056657/562949953421312), (-6176526630847251/562949953421312), (3273180087300779/562949953421312), (-5610069440986643/4503599627370496)]
def Ph31 : ℝ[X] := ofCoeffs [(2630412994402533/4503599627370496), (-2715186990257275/2251799813685248), (716327490698839/1125899906842624), (6842734621971475/2305843009213693952)]
def Qh31 : ℝ[X] := ofCoeffs [1, (-3591096978020049/1125899906842624), (7984716172356125/2251799813685248), (-3072155574661889/2251799813685248)]
def rho31 : ℝ := (5854679515581645/18014398509481984)
def G31 : ℝ[X] := Qg31.comp (X^2)+X*Pg31.comp (X^2)
def H31 : ℝ[X] := Qh31.comp (X^2)+X^3*Ph31.comp (X^2)
def A31 : ℝ[X] := G31*H31

theorem G31_coeffs : G31=ofCoeffs [1, (1162219258676257/36028797018963968), (-714498461211095/140737488355328), (-3319584381680765/4503599627370496), (5899689808056657/562949953421312), (2925838758887471/1125899906842624), (-6176526630847251/562949953421312), (-8395738696596451/2251799813685248), (3273180087300779/562949953421312), (1377388413819675/562949953421312), (-5610069440986643/4503599627370496), (-5514983533370323/9007199254740992)] := by
  norm_num [ofCoeffs,G31,Qg31,Pg31]
  <;> ring

theorem G31_positive (y : ℝ) (hy : |y|≤rho31) : 0<(G31).eval y := by
  rw [G31_coeffs]
  apply positive_on_gate _ ((5854679515581645/18014398509481984) : ℚ) (by norm_num)
  · norm_num [mass]
  · simpa [rho31] using hy

theorem H31_coeffs : H31=ofCoeffs [1, 0, (-3591096978020049/1125899906842624), (2630412994402533/4503599627370496), (7984716172356125/2251799813685248), (-2715186990257275/2251799813685248), (-3072155574661889/2251799813685248), (716327490698839/1125899906842624), 0, (6842734621971475/2305843009213693952)] := by
  norm_num [ofCoeffs,H31,Qh31,Ph31]
  <;> ring

theorem H31_positive (y : ℝ) (hy : |y|≤rho31) : 0<(H31).eval y := by
  rw [H31_coeffs]
  apply positive_on_gate _ ((5854679515581645/18014398509481984) : ℚ) (by norm_num)
  · norm_num [mass]
  · simpa [rho31] using hy

theorem A31_positive (y : ℝ) (hy : |y|≤rho31) : 0<A31.eval y := by
  simpa only [A31,eval_mul] using mul_pos (G31_positive y hy) (H31_positive y hy)

theorem D31_positive (y : ℝ) (hy : |y|≤rho31) :
    0<(LeanMath.Papers.V14RationalCertificate.denominator A31 (A31.comp (-X)) 31).eval y := by
  have hA := A31_positive y hy
  have hZ := A31_positive (-y) (by simpa using hy)
  have hy1 : |y|<1 := hy.trans_lt (by norm_num [rho31])
  have hs : 0<1-y^2 := by have hh := (sq_lt_one_iff_abs_lt_one y).mpr hy1; linarith
  simp only [LeanMath.Papers.V14RationalCertificate.denominator,eval_mul,eval_C,eval_sub,eval_one,eval_pow,eval_X,eval_comp,eval_neg]
  positivity

def Pg63 : ℝ[X] := ofCoeffs [(285942833483841/18014398509481984), (-791663851647947/1125899906842624), (6092604599284753/2251799813685248), (-4614369783133287/1125899906842624), (3168342736343539/1125899906842624), (-1653538931868589/2251799813685248)]
def Qg63 : ℝ[X] := ofCoeffs [1, (-5905438536761771/1125899906842624), (6304359452033579/562949953421312), (-6833194746441513/562949953421312), (7504238543247441/1125899906842624), (-6668370088884099/4503599627370496)]
def Ph63 : ℝ[X] := ofCoeffs [(5631058987706755/9007199254740992), (-2950693882793011/2251799813685248), (6367553444066999/9007199254740992), (8014348007499587/4611686018427387904)]
def Qh63 : ℝ[X] := ofCoeffs [1, (-7337541317189043/2251799813685248), (4179120343329473/1125899906842624), (-823164905107839/562949953421312)]
def rho63 : ℝ := (5944751508129055/18014398509481984)
def G63 : ℝ[X] := Qg63.comp (X^2)+X*Pg63.comp (X^2)
def H63 : ℝ[X] := Qh63.comp (X^2)+X^3*Ph63.comp (X^2)
def A63 : ℝ[X] := G63*H63

theorem G63_coeffs : G63=ofCoeffs [1, (285942833483841/18014398509481984), (-5905438536761771/1125899906842624), (-791663851647947/1125899906842624), (6304359452033579/562949953421312), (6092604599284753/2251799813685248), (-6833194746441513/562949953421312), (-4614369783133287/1125899906842624), (7504238543247441/1125899906842624), (3168342736343539/1125899906842624), (-6668370088884099/4503599627370496), (-1653538931868589/2251799813685248)] := by
  norm_num [ofCoeffs,G63,Qg63,Pg63]
  <;> ring

theorem G63_positive (y : ℝ) (hy : |y|≤rho63) : 0<(G63).eval y := by
  rw [G63_coeffs]
  apply positive_on_gate _ ((5944751508129055/18014398509481984) : ℚ) (by norm_num)
  · norm_num [mass]
  · simpa [rho63] using hy

theorem H63_coeffs : H63=ofCoeffs [1, 0, (-7337541317189043/2251799813685248), (5631058987706755/9007199254740992), (4179120343329473/1125899906842624), (-2950693882793011/2251799813685248), (-823164905107839/562949953421312), (6367553444066999/9007199254740992), 0, (8014348007499587/4611686018427387904)] := by
  norm_num [ofCoeffs,H63,Qh63,Ph63]
  <;> ring

theorem H63_positive (y : ℝ) (hy : |y|≤rho63) : 0<(H63).eval y := by
  rw [H63_coeffs]
  apply positive_on_gate _ ((5944751508129055/18014398509481984) : ℚ) (by norm_num)
  · norm_num [mass]
  · simpa [rho63] using hy

theorem A63_positive (y : ℝ) (hy : |y|≤rho63) : 0<A63.eval y := by
  simpa only [A63,eval_mul] using mul_pos (G63_positive y hy) (H63_positive y hy)

theorem D63_positive (y : ℝ) (hy : |y|≤rho63) :
    0<(LeanMath.Papers.V14RationalCertificate.denominator A63 (A63.comp (-X)) 63).eval y := by
  have hA := A63_positive y hy
  have hZ := A63_positive (-y) (by simpa using hy)
  have hy1 : |y|<1 := hy.trans_lt (by norm_num [rho63])
  have hs : 0<1-y^2 := by have hh := (sq_lt_one_iff_abs_lt_one y).mpr hy1; linarith
  simp only [LeanMath.Papers.V14RationalCertificate.denominator,eval_mul,eval_C,eval_sub,eval_one,eval_pow,eval_X,eval_comp,eval_neg]
  positivity

def Pg127 : ℝ[X] := ofCoeffs [(567382630219905/72057594037927936), (-6100765428185463/9007199254740992), (4681039844054039/2251799813685248), (-4950514592894081/2251799813685248), (7122293779889599/9007199254740992)]
def Qg127 : ℝ[X] := ofCoeffs [1, (-2435838703786577/562949953421312), (8126313488045631/1125899906842624), (-6164406955427261/1125899906842624), (1787696948608717/1125899906842624)]
def Ph127 : ℝ[X] := ofCoeffs [(2908763794178709/4503599627370496), (-7828884069294399/4503599627370496), (3496745127888725/2251799813685248), (-8097546923356063/18014398509481984), (-531452374632059/1152921504606846976)]
def Qh127 : ℝ[X] := ofCoeffs [1, (-8720618788043913/2251799813685248), (3227389807928951/562949953421312), (-33213075040327/8796093022208), (4126782527060099/4503599627370496)]
def rho127 : ℝ := (2386907802506363/9007199254740992)
def G127 : ℝ[X] := Qg127.comp (X^2)+X*Pg127.comp (X^2)
def H127 : ℝ[X] := Qh127.comp (X^2)+X^3*Ph127.comp (X^2)
def A127 : ℝ[X] := G127*H127

theorem G127_coeffs : G127=ofCoeffs [1, (567382630219905/72057594037927936), (-2435838703786577/562949953421312), (-6100765428185463/9007199254740992), (8126313488045631/1125899906842624), (4681039844054039/2251799813685248), (-6164406955427261/1125899906842624), (-4950514592894081/2251799813685248), (1787696948608717/1125899906842624), (7122293779889599/9007199254740992)] := by
  norm_num [ofCoeffs,G127,Qg127,Pg127]
  <;> ring

theorem G127_positive (y : ℝ) (hy : |y|≤rho127) : 0<(G127).eval y := by
  rw [G127_coeffs]
  apply positive_on_gate _ ((2386907802506363/9007199254740992) : ℚ) (by norm_num)
  · norm_num [mass]
  · simpa [rho127] using hy

theorem H127_coeffs : H127=ofCoeffs [1, 0, (-8720618788043913/2251799813685248), (2908763794178709/4503599627370496), (3227389807928951/562949953421312), (-7828884069294399/4503599627370496), (-33213075040327/8796093022208), (3496745127888725/2251799813685248), (4126782527060099/4503599627370496), (-8097546923356063/18014398509481984), 0, (-531452374632059/1152921504606846976)] := by
  norm_num [ofCoeffs,H127,Qh127,Ph127]
  <;> ring

theorem H127_positive (y : ℝ) (hy : |y|≤rho127) : 0<(H127).eval y := by
  rw [H127_coeffs]
  apply positive_on_gate _ ((2386907802506363/9007199254740992) : ℚ) (by norm_num)
  · norm_num [mass]
  · simpa [rho127] using hy

theorem A127_positive (y : ℝ) (hy : |y|≤rho127) : 0<A127.eval y := by
  simpa only [A127,eval_mul] using mul_pos (G127_positive y hy) (H127_positive y hy)

theorem D127_positive (y : ℝ) (hy : |y|≤rho127) :
    0<(LeanMath.Papers.V14RationalCertificate.denominator A127 (A127.comp (-X)) 127).eval y := by
  have hA := A127_positive y hy
  have hZ := A127_positive (-y) (by simpa using hy)
  have hy1 : |y|<1 := hy.trans_lt (by norm_num [rho127])
  have hs : 0<1-y^2 := by have hh := (sq_lt_one_iff_abs_lt_one y).mpr hy1; linarith
  simp only [LeanMath.Papers.V14RationalCertificate.denominator,eval_mul,eval_C,eval_sub,eval_one,eval_pow,eval_X,eval_comp,eval_neg]
  positivity

def Pg255 : ℝ[X] := ofCoeffs [(282578800148737/72057594037927936), (-3008652550691059/4503599627370496), (6408355908282357/4503599627370496), (-7100469721910749/9007199254740992)]
def Qg255 : ℝ[X] := ofCoeffs [1, (-940403833218299/281474976710656), (4397711867432937/1125899906842624), (-1778515545108755/1125899906842624)]
def Ph255 : ℝ[X] := ofCoeffs [(2955533787780529/4503599627370496), (-6344705236898053/9007199254740992), (1385662224309251/576460752303423488)]
def Qh255 : ℝ[X] := ofCoeffs [1, (-637255248754987/281474976710656), (6455868657287533/4503599627370496)]
def rho255 : ℝ := (607985949695017/4503599627370496)
def G255 : ℝ[X] := Qg255.comp (X^2)+X*Pg255.comp (X^2)
def H255 : ℝ[X] := Qh255.comp (X^2)+X^3*Ph255.comp (X^2)
def A255 : ℝ[X] := G255*H255

theorem G255_coeffs : G255=ofCoeffs [1, (282578800148737/72057594037927936), (-940403833218299/281474976710656), (-3008652550691059/4503599627370496), (4397711867432937/1125899906842624), (6408355908282357/4503599627370496), (-1778515545108755/1125899906842624), (-7100469721910749/9007199254740992)] := by
  norm_num [ofCoeffs,G255,Qg255,Pg255]
  <;> ring

theorem G255_positive (y : ℝ) (hy : |y|≤rho255) : 0<(G255).eval y := by
  rw [G255_coeffs]
  apply positive_on_gate _ ((607985949695017/4503599627370496) : ℚ) (by norm_num)
  · norm_num [mass]
  · simpa [rho255] using hy

theorem H255_coeffs : H255=ofCoeffs [1, 0, (-637255248754987/281474976710656), (2955533787780529/4503599627370496), (6455868657287533/4503599627370496), (-6344705236898053/9007199254740992), 0, (1385662224309251/576460752303423488)] := by
  norm_num [ofCoeffs,H255,Qh255,Ph255]
  <;> ring

theorem H255_positive (y : ℝ) (hy : |y|≤rho255) : 0<(H255).eval y := by
  rw [H255_coeffs]
  apply positive_on_gate _ ((607985949695017/4503599627370496) : ℚ) (by norm_num)
  · norm_num [mass]
  · simpa [rho255] using hy

theorem A255_positive (y : ℝ) (hy : |y|≤rho255) : 0<A255.eval y := by
  simpa only [A255,eval_mul] using mul_pos (G255_positive y hy) (H255_positive y hy)

theorem D255_positive (y : ℝ) (hy : |y|≤rho255) :
    0<(LeanMath.Papers.V14RationalCertificate.denominator A255 (A255.comp (-X)) 255).eval y := by
  have hA := A255_positive y hy
  have hZ := A255_positive (-y) (by simpa using hy)
  have hy1 : |y|<1 := hy.trans_lt (by norm_num [rho255])
  have hs : 0<1-y^2 := by have hh := (sq_lt_one_iff_abs_lt_one y).mpr hy1; linarith
  simp only [LeanMath.Papers.V14RationalCertificate.denominator,eval_mul,eval_C,eval_sub,eval_one,eval_pow,eval_X,eval_comp,eval_neg]
  positivity

end LeanMath.Papers.V14DeployedCoefficients
