import LeanMath.Basic
import LeanMath.Papers.AnalyticLimitFactor
import LeanMath.Papers.AnalyticReversion
import LeanMath.Papers.Bilateral
import LeanMath.Papers.BilateralHybrid
import LeanMath.Papers.BilateralLocal
import LeanMath.Papers.BilateralRange
import LeanMath.Papers.Bracket
import LeanMath.Papers.BranchConvergence
import LeanMath.Papers.BranchStructure
import LeanMath.Papers.BranchTaylor
import LeanMath.Papers.Cayley
import LeanMath.Papers.CayleyConvergence
import LeanMath.Papers.CayleyCubic
import LeanMath.Papers.CayleyHybrid
import LeanMath.Papers.CayleyLocal
import LeanMath.Papers.CayleyQuintic
import LeanMath.Papers.CertifiedConvergence
import LeanMath.Papers.CompactJacobian
import LeanMath.Papers.CompactPosynomial
import LeanMath.Papers.Comparison
import LeanMath.Papers.Corrections
import LeanMath.Papers.CoupledPowers
import LeanMath.Papers.CrossBracket
import LeanMath.Papers.CrossResidualObstruction
import LeanMath.Papers.CubicReversion
import LeanMath.Papers.CumulantCoefficient
import LeanMath.Papers.CumulantOrder
import LeanMath.Papers.CumulantPropagation
import LeanMath.Papers.DampedNewton
import LeanMath.Papers.Dyadic
import LeanMath.Papers.ExampleLaw
import LeanMath.Papers.ExponentialFamily
import LeanMath.Papers.ExtremalBracket
import LeanMath.Papers.ExtremalOptimality
import LeanMath.Papers.Family
import LeanMath.Papers.GlobalPosynomial
import LeanMath.Papers.GuardedBracket
import LeanMath.Papers.GuardedCenter
import LeanMath.Papers.GuardedCumulantSolver
import LeanMath.Papers.GuardedPosynomial
import LeanMath.Papers.GuardedRoot
import LeanMath.Papers.Hybrid
import LeanMath.Papers.IntervalIteration
import LeanMath.Papers.LocalOrder
import LeanMath.Papers.LogThompson
import LeanMath.Papers.MMatrixSign
import LeanMath.Papers.MonomialBoundary
import LeanMath.Papers.MonotoneIteration
import LeanMath.Papers.MovingTaylor
import LeanMath.Papers.MultivariateGuard
import LeanMath.Papers.NegativeBracket
import LeanMath.Papers.NewtonLocal
import LeanMath.Papers.PandrosionMinimal
import LeanMath.Papers.PolynomialPaths
import LeanMath.Papers.PosynomialCubic
import LeanMath.Papers.PosynomialDifferential
import LeanMath.Papers.PosynomialSystem
import LeanMath.Papers.ProportionalReadouts
import LeanMath.Papers.Raw
import LeanMath.Papers.RawConvergence
import LeanMath.Papers.RealBracket
import LeanMath.Papers.RealCorrections
import LeanMath.Papers.RectangleBilateral
import LeanMath.Papers.RectangleConstructible
import LeanMath.Papers.RectangleDecenteredArc
import LeanMath.Papers.RectangleDynamics
import LeanMath.Papers.RectangleFixedCircle
import LeanMath.Papers.RectangleFixedCircleStereo
import LeanMath.Papers.RectangleGeometry
import LeanMath.Papers.RectangleNewton
import LeanMath.Papers.RectanglePencils
import LeanMath.Papers.RectanglePencilsPade
import LeanMath.Papers.RectangleProjective
import LeanMath.Papers.RectangleProjectiveVerification
import LeanMath.Papers.RectangleRaw
import LeanMath.Papers.RectangleReports
import LeanMath.Papers.RectangleStereographic
import LeanMath.Papers.RectangleVerification
import LeanMath.Papers.RefinementOrdering
import LeanMath.Papers.Reflection
import LeanMath.Papers.SafeBracket
import LeanMath.Papers.SeriesReversion
import LeanMath.Papers.StrictBracket
import LeanMath.Papers.V14Acceptance
import LeanMath.Papers.V14AccumulationCheck
import LeanMath.Papers.V14AnalyticLocal
import LeanMath.Papers.V14AnalyticUniqueness
import LeanMath.Papers.V14BernsteinBasis
import LeanMath.Papers.V14BernsteinCertificate
import LeanMath.Papers.V14BinaryPowerCount
import LeanMath.Papers.V14Cell
import LeanMath.Papers.V14CenterInfinity
import LeanMath.Papers.V14Certified127
import LeanMath.Papers.V14Certified255
import LeanMath.Papers.V14Certified31
import LeanMath.Papers.V14Certified63
import LeanMath.Papers.V14Coefficients
import LeanMath.Papers.V14Comparison
import LeanMath.Papers.V14CompressedAnalytic
import LeanMath.Papers.V14Contact
import LeanMath.Papers.V14CoupledOutputs
import LeanMath.Papers.V14CubicEnclosure
import LeanMath.Papers.V14Defect
import LeanMath.Papers.V14DefectSeries
import LeanMath.Papers.V14DeployedAccumulation
import LeanMath.Papers.V14DeployedBudgets
import LeanMath.Papers.V14DeployedCoefficients
import LeanMath.Papers.V14DeployedPolynomials
import LeanMath.Papers.V14DeployedUniform
import LeanMath.Papers.V14DiagonalBounds
import LeanMath.Papers.V14DiagonalContact
import LeanMath.Papers.V14DiagonalConvergence
import LeanMath.Papers.V14DiagonalError
import LeanMath.Papers.V14DiagonalOrdering
import LeanMath.Papers.V14DiagonalPolynomials
import LeanMath.Papers.V14DiagonalRegularity
import LeanMath.Papers.V14DiagonalWronskian
import LeanMath.Papers.V14DyadicChoices
import LeanMath.Papers.V14Entry
import LeanMath.Papers.V14EntryAsymptotic
import LeanMath.Papers.V14EntryCount
import LeanMath.Papers.V14EntryFamily
import LeanMath.Papers.V14Fused
import LeanMath.Papers.V14Halley
import LeanMath.Papers.V14HalleyThresholds
import LeanMath.Papers.V14HomogeneousCheck
import LeanMath.Papers.V14Homography
import LeanMath.Papers.V14LegacyRemainders
import LeanMath.Papers.V14Local
import LeanMath.Papers.V14LocalRemainder
import LeanMath.Papers.V14Minimal1048575
import LeanMath.Papers.V14Minimal131071
import LeanMath.Papers.V14Minimal16383
import LeanMath.Papers.V14Minimal262143
import LeanMath.Papers.V14Minimal32767
import LeanMath.Papers.V14Minimal524287
import LeanMath.Papers.V14Minimal65535
import LeanMath.Papers.V14Minimal8191
import LeanMath.Papers.V14MinimalCheck
import LeanMath.Papers.V14OddRemainder
import LeanMath.Papers.V14OrdinaryError
import LeanMath.Papers.V14Pade
import LeanMath.Papers.V14PadeContact
import LeanMath.Papers.V14PadeGlobal
import LeanMath.Papers.V14PadeNormalization
import LeanMath.Papers.V14PadeTheorem
import LeanMath.Papers.V14PolynomialCheck
import LeanMath.Papers.V14PolynomialGate
import LeanMath.Papers.V14PowerError
import LeanMath.Papers.V14RationalCertificate
import LeanMath.Papers.V14RootAnalytic
import LeanMath.Papers.V14RootSeries
import LeanMath.Papers.V14ScalarSeries
import LeanMath.Papers.V14Segments127_0
import LeanMath.Papers.V14Segments127_1
import LeanMath.Papers.V14Segments127_113
import LeanMath.Papers.V14Segments127_129
import LeanMath.Papers.V14Segments127_145
import LeanMath.Papers.V14Segments127_161
import LeanMath.Papers.V14Segments127_17
import LeanMath.Papers.V14Segments127_177
import LeanMath.Papers.V14Segments127_193
import LeanMath.Papers.V14Segments127_209
import LeanMath.Papers.V14Segments127_225
import LeanMath.Papers.V14Segments127_241
import LeanMath.Papers.V14Segments127_255
import LeanMath.Papers.V14Segments127_33
import LeanMath.Papers.V14Segments127_49
import LeanMath.Papers.V14Segments127_65
import LeanMath.Papers.V14Segments127_81
import LeanMath.Papers.V14Segments127_97
import LeanMath.Papers.V14Segments255_0
import LeanMath.Papers.V14Segments255_1
import LeanMath.Papers.V14Segments255_113
import LeanMath.Papers.V14Segments255_129
import LeanMath.Papers.V14Segments255_145
import LeanMath.Papers.V14Segments255_161
import LeanMath.Papers.V14Segments255_17
import LeanMath.Papers.V14Segments255_177
import LeanMath.Papers.V14Segments255_193
import LeanMath.Papers.V14Segments255_209
import LeanMath.Papers.V14Segments255_225
import LeanMath.Papers.V14Segments255_241
import LeanMath.Papers.V14Segments255_255
import LeanMath.Papers.V14Segments255_33
import LeanMath.Papers.V14Segments255_49
import LeanMath.Papers.V14Segments255_65
import LeanMath.Papers.V14Segments255_81
import LeanMath.Papers.V14Segments255_97
import LeanMath.Papers.V14Segments31_0
import LeanMath.Papers.V14Segments31_1
import LeanMath.Papers.V14Segments31_113
import LeanMath.Papers.V14Segments31_129
import LeanMath.Papers.V14Segments31_145
import LeanMath.Papers.V14Segments31_161
import LeanMath.Papers.V14Segments31_17
import LeanMath.Papers.V14Segments31_177
import LeanMath.Papers.V14Segments31_193
import LeanMath.Papers.V14Segments31_209
import LeanMath.Papers.V14Segments31_225
import LeanMath.Papers.V14Segments31_241
import LeanMath.Papers.V14Segments31_255
import LeanMath.Papers.V14Segments31_33
import LeanMath.Papers.V14Segments31_49
import LeanMath.Papers.V14Segments31_65
import LeanMath.Papers.V14Segments31_81
import LeanMath.Papers.V14Segments31_97
import LeanMath.Papers.V14Segments63_0
import LeanMath.Papers.V14Segments63_1
import LeanMath.Papers.V14Segments63_113
import LeanMath.Papers.V14Segments63_129
import LeanMath.Papers.V14Segments63_145
import LeanMath.Papers.V14Segments63_161
import LeanMath.Papers.V14Segments63_17
import LeanMath.Papers.V14Segments63_177
import LeanMath.Papers.V14Segments63_193
import LeanMath.Papers.V14Segments63_209
import LeanMath.Papers.V14Segments63_225
import LeanMath.Papers.V14Segments63_241
import LeanMath.Papers.V14Segments63_255
import LeanMath.Papers.V14Segments63_33
import LeanMath.Papers.V14Segments63_49
import LeanMath.Papers.V14Segments63_65
import LeanMath.Papers.V14Segments63_81
import LeanMath.Papers.V14Segments63_97
import LeanMath.Papers.V14SeriesContact
import LeanMath.Papers.V14SeriesRecurrence
import LeanMath.Papers.V14Solver
import LeanMath.Papers.V14Truncation
import LeanMath.Papers.V14Uniform
import LeanMath.Papers.V14WeightedMeans
import LeanMath.Papers.V14WidthRemainders
import LeanMath.Papers.WidthComparison
import LeanMath.Papers.WidthLocal

import LeanMath.Papers.RectangleFastPower
import LeanMath.Papers.RectangleNativeNondegeneracy
