import LeanMath.Papers.RectangleProjectiveVerification
#print axioms LeanMath.Papers.RectangleProjective.positive_terms
#print axioms LeanMath.Papers.RectangleProjective.step_pos
#print axioms LeanMath.Papers.RectangleProjective.numerator_difference
#print axioms LeanMath.Papers.RectangleProjective.step_one
#print axioms LeanMath.Papers.RectangleProjective.hasDerivAt_step
#print axioms LeanMath.Papers.RectangleProjective.step_continuous
#print axioms LeanMath.Papers.RectangleProjective.unit_bound
#print axioms LeanMath.Papers.RectangleProjective.unit_increases
#print axioms LeanMath.Papers.RectangleProjective.unit_global
#print axioms LeanMath.Papers.RectangleProjective.step_scale
#print axioms LeanMath.Papers.RectangleProjective.global_with_root
#print axioms LeanMath.Papers.RectangleProjective.global_convergence
#print axioms LeanMath.Papers.RectangleProjective.order_four
#print axioms LeanMath.Papers.RectangleProjective.relative_order_four
#print axioms LeanMath.Papers.RectangleProjective.order_coefficient_negative
#print axioms LeanMath.Papers.RectangleProjective.D_on_ell
#print axioms LeanMath.Papers.RectangleProjective.D_on_ZE
#print axioms LeanMath.Papers.RectangleProjective.projection_det
#print axioms LeanMath.Papers.RectangleProjective.projection_unique
#print axioms LeanMath.Papers.RectangleProjective.D_on_support
#print axioms LeanMath.Papers.RectangleProjective.support_gap
#print axioms LeanMath.Papers.RectangleProjective.report_formula
#print axioms LeanMath.Papers.RectangleProjective.geometric_readout
#print axioms LeanMath.Papers.RectangleProjective.coordinates_over
#print axioms LeanMath.Papers.RectangleProjective.example_center
#print axioms LeanMath.Papers.RectangleProjective.example_D
#print axioms LeanMath.Papers.RectangleProjective.example_step
#print axioms LeanMath.Papers.RectangleProjective.D_right_of_A
#print axioms LeanMath.Papers.RectangleProjective.join_support_equiv
#print axioms LeanMath.Papers.RectangleProjective.construction_readout
#print axioms LeanMath.Papers.RectangleProjective.construction_exists
#print axioms LeanMath.Papers.RectangleProjective.inverse_correction
#print axioms LeanMath.Papers.RectangleProjective.pade_certificate
#print axioms LeanMath.Papers.RectangleProjective.homography_jet_unique
#print axioms LeanMath.Papers.RectangleProjective.bound_with_root
