import LeanMath.Papers.RectangleVerification

#print axioms LeanMath.Papers.RectangleBilateral.neutralAK_is_lower
#print axioms LeanMath.Papers.RectangleBilateral.neutralRaw_is_upper
#print axioms LeanMath.Papers.RectangleBilateral.neutralAK_dual
#print axioms LeanMath.Papers.RectangleBilateral.neutralRaw_dual
#print axioms LeanMath.Papers.RectangleBilateral.bilateral_AK_equals_original
#print axioms LeanMath.Papers.RectangleBilateral.diameter_endpoints
#print axioms LeanMath.Papers.RectangleBilateral.altitude_on_circle
#print axioms LeanMath.Papers.RectangleBilateral.altitude_unique
#print axioms LeanMath.Papers.RectangleBilateral.altitude_bilateral
#print axioms LeanMath.Papers.RectangleBilateral.bilateral_bracket
#print axioms LeanMath.Papers.RectangleBilateral.cubic_center
#print axioms LeanMath.Papers.RectangleConstructible.join_over
#print axioms LeanMath.Papers.RectangleConstructible.parallel_over
#print axioms LeanMath.Papers.RectangleConstructible.meet_over
#print axioms LeanMath.Papers.RectangleConstructible.levels_over
#print axioms LeanMath.Papers.RectangleConstructible.movingD_over
#print axioms LeanMath.Papers.RectangleConstructible.steps_over
#print axioms LeanMath.Papers.RectangleConstructible.altitude_over
#print axioms LeanMath.Papers.RectangleDynamics.ad_pos
#print axioms LeanMath.Papers.RectangleDynamics.ad_eq_halley
#print axioms LeanMath.Papers.RectangleDynamics.ad_global_convergence
#print axioms LeanMath.Papers.RectangleDynamics.hasDerivAt_ad
#print axioms LeanMath.Papers.RectangleDynamics.ad_order_three
#print axioms LeanMath.Papers.RectangleDynamics.ad_order_coefficient_pos
#print axioms LeanMath.Papers.RectangleDynamics.ad_scale
#print axioms LeanMath.Papers.RectangleDynamics.ad_relative_order_three
#print axioms LeanMath.Papers.RectangleGeometry.join_left
#print axioms LeanMath.Papers.RectangleGeometry.join_right
#print axioms LeanMath.Papers.RectangleGeometry.parallel_through
#print axioms LeanMath.Papers.RectangleGeometry.parallel_direction
#print axioms LeanMath.Papers.RectangleGeometry.graph_proper
#print axioms LeanMath.Papers.RectangleGeometry.graph_on
#print axioms LeanMath.Papers.RectangleGeometry.meet_on
#print axioms LeanMath.Papers.RectangleGeometry.intersection_unique
#print axioms LeanMath.Papers.RectangleGeometry.chain_horizontal
#print axioms LeanMath.Papers.RectangleGeometry.chain_left
#print axioms LeanMath.Papers.RectangleGeometry.chain_diagonal
#print axioms LeanMath.Papers.RectangleGeometry.chain_step
#print axioms LeanMath.Papers.RectangleGeometry.chain_step_unique
#print axioms LeanMath.Papers.RectangleGeometry.chain_horizontal_unique
#print axioms LeanMath.Papers.RectangleGeometry.report_incidence
#print axioms LeanMath.Papers.RectangleGeometry.report_unique
#print axioms LeanMath.Papers.RectangleGeometry.report_readout
#print axioms LeanMath.Papers.RectangleGeometry.horizontal_report
#print axioms LeanMath.Papers.RectangleNewton.ak_pos
#print axioms LeanMath.Papers.RectangleNewton.ak_one
#print axioms LeanMath.Papers.RectangleNewton.ak_unit_bound
#print axioms LeanMath.Papers.RectangleNewton.ak_unit_increases
#print axioms LeanMath.Papers.RectangleNewton.ak_unit_global
#print axioms LeanMath.Papers.RectangleNewton.ak_scale
#print axioms LeanMath.Papers.RectangleNewton.ak_global_with_root
#print axioms LeanMath.Papers.RectangleNewton.ak_global_convergence
#print axioms LeanMath.Papers.RectangleNewton.hasDerivAt_ak
#print axioms LeanMath.Papers.RectangleNewton.ak_order_two
#print axioms LeanMath.Papers.RectangleNewton.ak_relative_order_two
#print axioms LeanMath.Papers.RectangleRaw.sum_identity
#print axioms LeanMath.Papers.RectangleRaw.raw_incidence
#print axioms LeanMath.Papers.RectangleRaw.raw_gap
#print axioms LeanMath.Papers.RectangleRaw.raw_unique
#print axioms LeanMath.Papers.RectangleRaw.raw_readout
#print axioms LeanMath.Papers.RectangleRaw.raw_neutral
#print axioms LeanMath.Papers.RectangleRaw.raw_neutral_degenerate
#print axioms LeanMath.Papers.RectangleReports.green_through_M
#print axioms LeanMath.Papers.RectangleReports.green_through_E
#print axioms LeanMath.Papers.RectangleReports.AK_through_K
#print axioms LeanMath.Papers.RectangleReports.AD_through_D
#print axioms LeanMath.Papers.RectangleReports.through_A
#print axioms LeanMath.Papers.RectangleReports.D_is_fixed_translation
#print axioms LeanMath.Papers.RectangleReports.D_cubic_two
#print axioms LeanMath.Papers.RectangleReports.D_compass_transfer
#print axioms LeanMath.Papers.RectangleReports.ak_gap
#print axioms LeanMath.Papers.RectangleReports.ad_gap
#print axioms LeanMath.Papers.RectangleReports.denominators_pos
#print axioms LeanMath.Papers.RectangleReports.gaps_pos
#print axioms LeanMath.Papers.RectangleReports.ak_report
#print axioms LeanMath.Papers.RectangleReports.ad_report
#print axioms LeanMath.Papers.RectangleReports.ak_geometric_readout
#print axioms LeanMath.Papers.RectangleReports.ad_geometric_readout
#print axioms LeanMath.Papers.RectangleReports.reports_exist_unique
#print axioms LeanMath.Papers.RectangleVerification.raw_matches_existing
#print axioms LeanMath.Papers.RectangleVerification.raw_global
#print axioms LeanMath.Papers.RectangleVerification.target_identity
#print axioms LeanMath.Papers.RectangleVerification.ad_visible_convergence
#print axioms LeanMath.Papers.RectangleVerification.ak_visible_convergence
#print axioms LeanMath.Papers.RectangleVerification.cubic_preview_D
#print axioms LeanMath.Papers.RectangleVerification.cubic_preview_AD
#print axioms LeanMath.Papers.RectangleVerification.cubic_preview_AK
#print axioms LeanMath.Papers.RectangleVerification.cubic_preview_intersection
