import { chromium } from 'playwright';
import fs from 'node:fs';
const output=process.env.PREVIEW_OUTPUT || '.ci/browser';
fs.mkdirSync(output,{recursive:true});
(async()=>{const b=await chromium.launch({...(process.env.PLAYWRIGHT_CHANNEL ? {channel:process.env.PLAYWRIGHT_CHANNEL}:{}),headless:true});const page=await b.newPage({viewport:{width:1280,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(page.url()+': '+e.message));await page.goto(process.env.PREVIEW_URL || 'http://127.0.0.1:8765/');await page.waitForFunction(()=>document.getElementById('next-value').textContent!=='—');
for(const mode of ['AK','AD','projective','arc','halley','pade','circle','AKfast','ADfast','projectiveFast','arcFast']){await page.selectOption('#method',mode);if(await page.locator('#error').isVisible())throw Error(mode+': '+await page.locator('#error').innerText());await page.locator('#stage').fill('0');await page.locator('#stage').dispatchEvent('input');await page.click('#forward');await page.click('#iterate');await page.click('#reset');}
await page.selectOption('#method','circle');await page.selectOption('#chart','uniform');await page.screenshot({path:`${output}/gallery-uniform.png`,fullPage:true});await page.selectOption('#chart','compact');await page.selectOption('#view','sphere');await page.locator('#yaw').fill('50');await page.locator('#yaw').dispatchEvent('input');await page.screenshot({path:`${output}/gallery-sphere.png`,fullPage:true});
await page.selectOption('#example','initial');if(!await page.locator('#warning').isVisible())throw Error('Missing infinity warning');if(await page.locator('#view').inputValue()!=='sphere')throw Error('No automatic sphere');await page.selectOption('#view','plane');await page.click('#iterate');if(await page.locator('#view').inputValue()!=='plane')throw Error('Manual view overridden');await page.selectOption('#example','outside');if(!await page.locator('#error').isVisible())throw Error('Missing domain error');await page.click('#reset');await page.click('#normalize');if(await page.locator('#error').isVisible())throw Error('Normalization failed');
await page.selectOption('#method','AKfast');await page.locator('#degree').fill('1024');await page.locator('#state').fill(String(Math.exp(Math.log(.4)/1024)));await page.locator('#state').dispatchEvent('change');if(await page.locator('#error').isVisible())throw Error('Large degree failed');if(!(await page.locator('#fast-status').innerText()).includes('10 multiplications contre 1023'))throw Error('Wrong binary count');await page.click('#normalize-optimal');if(await page.locator('#error').isVisible())throw Error('Adaptive failed');if(!(await page.locator('#adaptive-status').innerText()).includes('score'))throw Error('Missing metadata');
await page.emulateMedia({colorScheme:'dark'});await page.screenshot({path:`${output}/binary-dark.png`,fullPage:true});await page.emulateMedia({colorScheme:'light'});await page.screenshot({path:`${output}/binary-light.png`,fullPage:true});
// Recover an arbitrary unusable state through explicit initialization (not a silent restart).
await page.selectOption('#method','AKfast');await page.locator('#degree').fill('1000000');await page.locator('#target').fill('500000');await page.locator('#state').fill('.75');await page.locator('#state').dispatchEvent('change');if(!await page.locator('#error').isVisible())throw Error('Expected unusable starting state');
await page.click('#initialize');if(await page.locator('#error').isVisible())throw Error('Initialization failed');if(!await page.locator('#initialization-status').isVisible())throw Error('Missing initialization certificate');
const calibrated=Number(await page.locator('#target').inputValue());if(calibrated<1||calibrated>2)throw Error('Unbounded calibrated X');
for(let i=0;i<12&&!await page.locator('#iterate').isDisabled();i++)await page.click('#iterate');
if(await page.locator('#error').isVisible())throw Error('Initialized iteration failed');if(!await page.locator('#iterate').isDisabled())throw Error('Missing precision stop');
await page.screenshot({path:`${output}/initialized-million.png`,fullPage:true});
await page.setViewportSize({width:360,height:900});await page.screenshot({path:`${output}/gallery-mobile.png`,fullPage:true});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);if(overflow)throw Error('Mobile overflow');
const links=await page.locator('.gallery-links a').evaluateAll(a=>a.map(x=>x.href));for(const url of links){await page.goto(url);await page.waitForTimeout(150);if((await page.locator('body').innerText()).includes('Error response'))throw Error('Missing '+url);}
if(errors.length)throw Error(errors.join('\n'));console.log(JSON.stringify({status:'PASS',methods:11,archive_previews:links.length,mobile_width:360,infinity_and_domain_checked:true}));await b.close();})().catch(e=>{console.error(e);process.exit(1)});
