"""MA, AK, AD and projective AD: retain the original triangle mechanism.

Points are computed from joins/parallels/intersections by the archived geometry
routine; the scalar formulas are checked only after the readout is constructed.
The decentered fifth drawing is generated by draw_figures.py.
"""
from pathlib import Path
import importlib.util
import json
import numpy as np
import mpmath as mp
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

HERE=Path(__file__).resolve().parent
spec=importlib.util.spec_from_file_location('arc_geometry',HERE.parent/'reciprocal_geometry_v20/src/decentered/verify.py')
geom=importlib.util.module_from_spec(spec);spec.loader.exec_module(geom)
mp.mp.dps=80
BLUE='#176B9B';GREEN='#398465';ORANGE='#bd5a20';GRAY='#b9c3c8';RED='#c5a29b';INK='#253640'
plt.rcParams.update({'font.family':'DejaVu Sans','font.size':11,'pdf.fonttype':42})
def seg(ax,a,b,c=GRAY,lw=1,ls='-'):
    ax.plot(*np.array([a,b],float).T,color=c,lw=lw,ls=ls)
def point(ax,p,label,off):
    p=np.array(p,float);ax.plot(*p,'o',ms=4,color=INK)
    ax.annotate(label,p,xytext=off,textcoords='offset points',fontsize=11)
checks={}
for mode in ['MA','AK','AD','projective']:
    g=geom.geometry(3,2,mp.mpf(3)/4,'AK' if mode=='MA' else mode)
    pts=g['points'];s=mp.mpf(3)/4;t=2*s**3
    if mode=='MA':
        # The original MA support is MB in the uniform O,A,B,C convention.
        support=geom.join(pts['M'],pts['B'])
        T=geom.cross(geom.parallel(g['green'],pts['P']),support)
        out=geom.cross(geom.parallel(geom.join(pts['C'],pts['B']),T),geom.join(pts['A'],pts['B']))
        pts.update(T=T,Pnext=out)
        expected=1-1/(2*sum(s**j for j in range(3)))
    elif mode=='AK':expected=3*s/(2+t)
    elif mode=='AD':expected=s*(4+2*t)/(2+4*t)
    else:expected=s*6*(5*t+4)/(4*t*t+40*t+10)
    actual=1-pts['Pnext'][1]/4
    assert abs(actual-expected)<mp.mpf('1e-70'),mode
    checks[mode]={'p':3,'X':2,'s':'0.75','readout':mp.nstr(actual,35),'residual':mp.nstr(abs(actual-expected),5)}
    fig,ax=plt.subplots(figsize=(4.3,5.2),layout='constrained')
    ax.set_aspect('equal');ax.axis('off')
    for a,b in [('O','A'),('A','B'),('B','C'),('C','O'),('O','B')]:seg(ax,pts[a],pts[b])
    for a,b in g['chain']:seg(ax,a,(2,a[1]),GRAY,.8)
    for a,b in g['red']:seg(ax,a,b,RED,.9)
    seg(ax,pts['M'],pts['E'],GREEN,1.8);seg(ax,pts['P'],pts['T'],GREEN,1.8)
    seg(ax,pts['T'],pts['Pnext'],BLUE,1.8)
    labels=['O','A','B','C','M','E','P','T','Pnext']
    limits=(-.55,2.65,-.8,4.5)
    if mode=='MA':
        seg(ax,pts['M'],pts['B'],BLUE,2)
    elif mode=='AK':
        seg(ax,pts['A'],pts['K'],BLUE,2);labels+=['K']
    elif mode=='AD':
        seg(ax,pts['A'],pts['D'],BLUE,2);labels+=['D','F']
        F=np.array(pts['F'],float);r=float(g['radius']);theta=np.linspace(-np.pi*.83,-np.pi*.17,150)
        ax.plot(F[0]+r*np.cos(theta),F[1]+r*np.sin(theta),c=ORANGE,lw=1.8)
        seg(ax,pts['F'],pts['D'],ORANGE,1,':');seg(ax,pts['A'],pts['E'],ORANGE,2)
        limits=(-1.8,2.8,-2.3,4.5)
    else:
        seg(ax,pts['A'],pts['D'],BLUE,2);seg(ax,pts['E'],pts['D'],ORANGE,1.8)
        y=float(pts['D'][1]);seg(ax,(-.2,y),(5.1,y),ORANGE,1,'--');ax.text(.15,y+.28,r'$\ell$',color=ORANGE)
        labels+=['Z','D'];limits=(-.55,5.5,-.6,12)
        # A second equal-axis view keeps the readout legible beneath the distant support.
        inset=ax.inset_axes([.02,.43,.4,.34]);inset.set_aspect('equal');inset.set_xlim(-.6,2.9);inset.set_ylim(0,2.8)
        inset.set_xticks([]);inset.set_yticks([]);inset.set_title('Readout detail',fontsize=9)
        for a,b in [('M','E'),('P','T')]:seg(inset,pts[a],pts[b],GREEN,1.5)
        seg(inset,pts['T'],pts['Pnext'],BLUE,1.5)
        seg(inset,pts['A'],pts['T'],BLUE,1)
        for k,o in [('P',(5,3)),('Pnext',(5,-13)),('T',(-15,-12))]:point(inset,pts[k],r'$P^+$' if k=='Pnext' else k,o)
    offsets={'O':(-18,5),'A':(6,6),'B':(5,-15),'C':(-15,-15),'M':(-19,-2),'E':(7,6),'P':(7,2),'T':(-16,-12),'Pnext':(7,-13),'K':(-4,-15),'D':(-27,5),'F':(6,-3),'Z':(7,2)}
    for name in labels:
        if mode=='AD' and name=='C':continue # F=C in this cubic example.
        label={'Pnext':r'$P^+$','F':r'$O_{AD}=C$','D':r'$D_{AD}$' if mode=='AD' else r'$D_{proj}$','Z':r'$Z_{proj}$'}.get(name,name)
        if mode=='MA' and name=='B':
            label=r'$B=A_{lin}$';offsets['B']=(-22,-18)
        point(ax,pts[name],label,offsets[name])
    ax.set_xlim(*limits[:2]);ax.set_ylim(*limits[2:])
    fig.savefig(HERE/f'figures/pandrosion_{mode.lower()}.pdf')
    fig.savefig(HERE/f'figures/pandrosion_{mode.lower()}.png',dpi=180)
    plt.close(fig)
(HERE/'pandrosion_figure_checks.json').write_text(json.dumps(checks,indent=2)+'\n')
print('PASS: four Pandrosion figures from intersections; scalar readouts agree at 70 digits')
