import LeanMath.Papers.RectangleStereographic
#print axioms LeanMath.Papers.RectangleProjective.positive_terms
#print axioms LeanMath.Papers.RectangleProjective.step_pos
#print axioms LeanMath.Papers.RectangleProjective.numerator_difference
#print axioms LeanMath.Papers.RectangleProjective.step_one
#print axioms LeanMath.Papers.RectangleProjective.hasDerivAt_step
#print axioms LeanMath.Papers.RectangleProjective.step_continuous
#print axioms LeanMath.Papers.RectangleProjective.unit_bound
#print axioms LeanMath.Papers.RectangleProjective.unit_increases
#print axioms LeanMath.Papers.RectangleProjective.unit_global
#print axioms LeanMath.Papers.RectangleProjective.step_scale
#print axioms LeanMath.Papers.RectangleProjective.global_with_root
#print axioms LeanMath.Papers.RectangleProjective.global_convergence
#print axioms LeanMath.Papers.RectangleProjective.order_four
#print axioms LeanMath.Papers.RectangleProjective.relative_order_four
#print axioms LeanMath.Papers.RectangleProjective.order_coefficient_negative
#print axioms LeanMath.Papers.RectangleProjective.D_on_ell
#print axioms LeanMath.Papers.RectangleProjective.D_on_ZE
#print axioms LeanMath.Papers.RectangleProjective.projection_det
#print axioms LeanMath.Papers.RectangleProjective.projection_unique
#print axioms LeanMath.Papers.RectangleProjective.D_on_support
#print axioms LeanMath.Papers.RectangleProjective.support_gap
#print axioms LeanMath.Papers.RectangleProjective.report_formula
#print axioms LeanMath.Papers.RectangleProjective.geometric_readout
#print axioms LeanMath.Papers.RectangleProjective.coordinates_over
#print axioms LeanMath.Papers.RectangleProjective.example_center
#print axioms LeanMath.Papers.RectangleProjective.example_D
#print axioms LeanMath.Papers.RectangleProjective.example_step
#print axioms LeanMath.Papers.RectangleProjective.D_right_of_A
#print axioms LeanMath.Papers.RectangleProjective.join_support_equiv
#print axioms LeanMath.Papers.RectangleProjective.construction_readout
#print axioms LeanMath.Papers.RectangleProjective.construction_exists
#print axioms LeanMath.Papers.RectangleProjective.inverse_correction
#print axioms LeanMath.Papers.RectangleProjective.pade_certificate
#print axioms LeanMath.Papers.RectangleProjective.homography_jet_unique
#print axioms LeanMath.Papers.RectangleProjective.bound_with_root
#print axioms LeanMath.Papers.RectanglePencils.hub_on_top
#print axioms LeanMath.Papers.RectanglePencils.left_on_axis
#print axioms LeanMath.Papers.RectanglePencils.right_on_axis
#print axioms LeanMath.Papers.RectanglePencils.multiply_incidence
#print axioms LeanMath.Papers.RectanglePencils.multiply_det
#print axioms LeanMath.Papers.RectanglePencils.multiply_unique
#print axioms LeanMath.Papers.RectanglePencils.divide_incidence
#print axioms LeanMath.Papers.RectanglePencils.divide_unique
#print axioms LeanMath.Papers.RectanglePencils.chain_start
#print axioms LeanMath.Papers.RectanglePencils.chain_step
#print axioms LeanMath.Papers.RectanglePencils.chain_unscale
#print axioms LeanMath.Papers.RectanglePencils.chain_center
#print axioms LeanMath.Papers.RectanglePencils.projector_incidence
#print axioms LeanMath.Papers.RectanglePencils.projector_gap
#print axioms LeanMath.Papers.RectanglePencils.projector_unique
#print axioms LeanMath.Papers.RectanglePencils.four_join_readout
#print axioms LeanMath.Papers.RectanglePencils.halley_factor_formula
#print axioms LeanMath.Papers.RectanglePencils.halley_center_a
#print axioms LeanMath.Papers.RectanglePencils.halley_center_b
#print axioms LeanMath.Papers.RectanglePencils.halley_root_factors
#print axioms LeanMath.Papers.RectanglePencils.halley_global
#print axioms LeanMath.Papers.RectanglePencils.example_q
#print axioms LeanMath.Papers.RectanglePencils.example_Za
#print axioms LeanMath.Papers.RectanglePencils.example_Zb
#print axioms LeanMath.Papers.RectanglePencils.example_readout
#print axioms LeanMath.Papers.RectanglePencils.projectors_over
#print axioms LeanMath.Papers.RectanglePencils.chain_center_unique
#print axioms LeanMath.Papers.RectanglePencils.chain_cycle
#print axioms LeanMath.Papers.RectanglePencils.halley_construction_readout
#print axioms LeanMath.Papers.RectanglePencils.initial_chart_failure
#print axioms LeanMath.Papers.RectanglePencils.example_correction_chart_failure
#print axioms LeanMath.Papers.RectanglePencils.halley_relative_order_three
#print axioms LeanMath.Papers.RectanglePencilsPade.coeff_pos
#print axioms LeanMath.Papers.RectanglePencilsPade.terms_pos
#print axioms LeanMath.Papers.RectanglePencilsPade.step_pos
#print axioms LeanMath.Papers.RectanglePencilsPade.difference
#print axioms LeanMath.Papers.RectanglePencilsPade.one
#print axioms LeanMath.Papers.RectanglePencilsPade.hasDerivAt_step
#print axioms LeanMath.Papers.RectanglePencilsPade.continuousAt_step
#print axioms LeanMath.Papers.RectanglePencilsPade.monotone_positive
#print axioms LeanMath.Papers.RectanglePencilsPade.unit_moves
#print axioms LeanMath.Papers.RectanglePencilsPade.unit_global
#print axioms LeanMath.Papers.RectanglePencilsPade.scale_step
#print axioms LeanMath.Papers.RectanglePencilsPade.global_with_root
#print axioms LeanMath.Papers.RectanglePencilsPade.global_convergence
#print axioms LeanMath.Papers.RectanglePencilsPade.order_five
#print axioms LeanMath.Papers.RectanglePencilsPade.relative_order_five
#print axioms LeanMath.Papers.RectanglePencilsPade.order_coefficient_pos
#print axioms LeanMath.Papers.RectanglePencilsPade.disc_formula
#print axioms LeanMath.Papers.RectanglePencilsPade.disc_pos
#print axioms LeanMath.Papers.RectanglePencilsPade.roots_pos
#print axioms LeanMath.Papers.RectanglePencilsPade.roots_sum_product
#print axioms LeanMath.Papers.RectanglePencilsPade.factorization
#print axioms LeanMath.Papers.RectanglePencilsPade.normalized_factor
#print axioms LeanMath.Papers.RectanglePencilsPade.pair_ratio
#print axioms LeanMath.Papers.RectanglePencilsPade.two_factor_formula
#print axioms LeanMath.Papers.RectanglePencilsPade.roots_constructible
#print axioms LeanMath.Papers.RectanglePencilsPade.factor_projectors_constructible
#print axioms LeanMath.Papers.RectangleStereographic.denominator_pos
#print axioms LeanMath.Papers.RectangleStereographic.on_circle
#print axioms LeanMath.Papers.RectangleStereographic.north
#print axioms LeanMath.Papers.RectangleStereographic.affine
#print axioms LeanMath.Papers.RectangleStereographic.scale_invariant
#print axioms LeanMath.Papers.RectangleStereographic.on_sphere
#print axioms LeanMath.Papers.RectangleStereographic.multiply_horizontal
#print axioms LeanMath.Papers.RectangleStereographic.divide_horizontal
